runtime: python
env: flex
entrypoint: python main.py
runtime_config:
  python_version: 3
manual_scaling:
  instances: 1
resources:
  cpu: 2  
  memory_gb: 5
  disk_size_gb: 10
vpc_access_connector:
  name: "projects/murosys/locations/us-east4/connectors/connect-to-sql"

